// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Aperture = (function() {
    function Aperture(params) {
      var key, value;
      for (key in params) {
        value = params[key];
        this["" + key] = value;
      }
      this.print();
    }

    Aperture.prototype.print = function() {
      var p;
      p = "aperture " + this.code + " is a " + this.shape + " with ";
      switch (this.shape) {
        case 'C':
          p += "dia: " + this.dia;
          break;
        case 'R':
        case 'O':
          p += "x size: " + this.sizeX + ", y size: " + this.sizeY;
          break;
        case 'P':
          p += "circumscribed dia: " + this.dia + ", points: " + this.points;
          if (this.rotation != null) {
            p += ", rotation: " + this.rotation;
          }
          break;
        default:
          p += 'macro stuff';
      }
      if (this.holeX != null) {
        if (this.holeY == null) {
          p += ", hole dia: " + this.holeX;
        } else {
          p += ", hole x size: " + this.holeX + ", hole y size " + this.holeY;
        }
      }
      return console.log(p);
    };

    return Aperture;

  })();

}).call(this);

//# sourceMappingURL=aperture.map
