// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Aperture = (function() {
    function Aperture(code, shape, params) {
      this.code = code;
      this.shape = shape;
      this.params = params;
      this.print();
    }

    Aperture.prototype.print = function() {
      var p;
      p = "aperture " + this.code + " is a " + this.shape + " with ";
      switch (this.shape) {
        case 'C':
          p += "dia: " + this.params.dia;
          break;
        case 'R':
        case 'O':
          p += "x size: " + this.params.sizeX + ", y size: " + this.params.sizeY;
          break;
        case 'P':
          p += "circumscribed dia: " + this.params.dia + ", points: " + this.params.points;
          if (this.params.rotation != null) {
            p += ", rotation: " + this.params.rotation;
          }
          break;
        default:
          p += 'macro stuff';
      }
      if (this.params.holeX != null) {
        if (this.params.holeY == null) {
          p += ", hole dia: " + this.params.holeX;
        } else {
          p += ", hole x size: " + this.params.holeX + ", hole y size " + this.params.holeY;
        }
      }
      return console.log(p);
    };

    return Aperture;

  })();

}).call(this);

//# sourceMappingURL=aperture.map
