// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Aperture = (function() {
    function Aperture(code, shape, params) {
      this.code = code;
      this.shape = shape;
      this.params = params;
      console.log("Aperture " + this.code + " was created and is a " + this.shape);
    }

    return Aperture;

  })();

}).call(this);

//# sourceMappingURL=aperture.map
