// Generated by CoffeeScript 1.7.1
(function() {
  var fileToSVG, handleFileSelect, readFileToDiv;

  fileToSVG = function(file) {
    var layer, p;
    console.log('converting to svg');
    p = new Plotter(file);
    return layer = p.plot();
  };

  readFileToDiv = function(event) {
    var drawDiv, layer;
    if (event.target.readyState === FileReader.DONE) {
      layer = fileToSVG(event.target.result);
      drawDiv = document.createElement('div');
      drawDiv.id = "layer-" + layer.name;
      drawDiv["class"] = 'layer-div';
      document.getElementById('layers').insertBefore(drawDiv, null);
      return layer.draw(drawDiv.id);
    }
  };

  handleFileSelect = function(event) {
    var f, importFiles, output, reader, _i, _j, _len, _len1, _results;
    importFiles = event.target.files;
    output = [];
    for (_i = 0, _len = importFiles.length; _i < _len; _i++) {
      f = importFiles[_i];
      output.push('<li><strong>', escape(f.name), '</li>');
    }
    document.getElementById('list').innerHTML = '<ul>' + output.join('') + '</ul>';
    _results = [];
    for (_j = 0, _len1 = importFiles.length; _j < _len1; _j++) {
      f = importFiles[_j];
      reader = new FileReader();
      reader.addEventListener('loadend', readFileToDiv, false);
      _results.push(reader.readAsText(f));
    }
    return _results;
  };

  document.getElementById('files').addEventListener('change', handleFileSelect, false);

}).call(this);

//# sourceMappingURL=app.map
