// Generated by CoffeeScript 1.7.1
(function() {
  var fileToSVG, handleFileSelect, readFileToDiv;

  fileToSVG = function(file) {
    var gerberMatch, line, lines;
    lines = file.split("\n");
    line = 0;
    while (lines[line].match(/^G04.*$/)) {
      line++;
    }
    console.log(lines[0]);
    console.log(lines[line]);
    gerberMatch = /^%FS[L,T,D][A,I](N\d+)?(G\d+)?X[0-5]{2}Y[0-5]{2}(D\d+)?(M\d+)?\*%$/;
    if (lines[line].match(gerberMatch)) {
      return "it's a gerber";
    } else {
      return "it's not a gerber";
    }
  };

  readFileToDiv = function(event) {
    var textDiv;
    if (event.target.readyState === FileReader.DONE) {
      textDiv = document.createElement('p');
      textDiv.innerHTML = fileToSVG(event.target.result);
      return document.getElementById('file-contents').insertBefore(textDiv, null);
    }
  };

  handleFileSelect = function(event) {
    var f, importFiles, output, reader, _i, _j, _len, _len1, _results;
    importFiles = event.target.files;
    output = [];
    for (_i = 0, _len = importFiles.length; _i < _len; _i++) {
      f = importFiles[_i];
      output.push('<li><strong>', escape(f.name), '</li>');
    }
    document.getElementById('list').innerHTML = '<ul>' + output.join('') + '</ul>';
    _results = [];
    for (_j = 0, _len1 = importFiles.length; _j < _len1; _j++) {
      f = importFiles[_j];
      reader = new FileReader();
      reader.addEventListener('loadend', readFileToDiv, false);
      _results.push(reader.readAsText(f));
    }
    return _results;
  };

  document.getElementById('files').addEventListener('change', handleFileSelect, false);

}).call(this);

//# sourceMappingURL=filereader.map
