#! /bin/sh
# compile the necessary files and then serve them

# get script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# compile and run static server on default port (8080)
cd ${DIR}/..
scripts/compile
static
